"""StudySpec: Apex + v8 (lambda=8) vs Apex + released v7 (lambda=4), group-sequential Tier 2.

Instantiation of ``research/sequential_strict_template`` (method
``strict-sequential-obf-bonferroni-v1``). Pre-registration: ``protocol.md`` beside this file;
the operating-characteristics report and the look-1 band-cost report are generated by
``preregistration.py`` from the closed v8 Tier-1 screen and are frozen by sha256 in the intent.

Arms (hero only; opponents never carry a veto; both arms run
``tournament_eval.rollout(hero_safety_veto=True)`` with the install routed through
``dev_screen.hero_veto_installer`` exactly as the v7 strict package and the v8 screen did):

* incumbent: champion + ``free-space-veto/v7-space-preference(lambda=4.0)``, the released
  Watch-hero veto, bound fail closed to the v7 STRICT_PASS receipt (receipt bytes, method,
  descriptor, checkpoint and the four veto source sha256s it records);
* candidate: champion + ``free-space-veto/v8-space-and-head(lambda=8.0)``, bound by the sha256s
  of every veto module it executes (v8, v7, v6, v5, v4, v3, v2), pinned below and equal to the
  bytes at the v8 screen commit. Installed WITHOUT the screen's diagnostic-only
  ``reference_lambda`` (not part of the descriptor; it never changes a decision).

Nothing here changes a champion, default, config, released veto or deployment.
"""

from __future__ import annotations

import functools
import hashlib
import json
from pathlib import Path
from typing import Any, Dict, List, Mapping, Sequence

from research.apex_safety_20260926 import dev_screen
from research.sequential_strict_template.sequential_runner import (
    DEFAULT_CLOSURE_ROOTS,
    N_MAX_CAP,
    StrictRunError,
    StudySpec,
    require,
    seed_bank,
    survival_bands,
)

HERE = Path(__file__).resolve().parent
PACKAGE = "research/apex_veto_v8_strict_20261003"
STUDY_ID = "apex-veto-v8-strict-20261003"
SCHEMA = "apex-veto-v8-strict-sequential/v1"
NAMESPACES = {
    "calibration": "apex-veto-v8-strict-dev-v1",
    "final": "apex-veto-v8-strict-final-v1",
}
MIXES = tuple(dev_screen.MIXES)
SCRIPTED_MIX = "scripted"
PRIMARY_METRIC = "mass_integral"
NI_FRACTION = 0.03  # as the v7 strict: delta_NI = 0.03 x calibration incumbent scripted mean
BAND_BELOW = 0.02  # as the v7 strict: candidate survival_fraction in [ref - 0.02, ref + 1]
BAND_ABOVE = 1.0
N_CALIBRATION = 16  # as the v7 strict (16 dev worlds x 3 mixes, incumbent only)
HORIZON = dev_screen.HORIZON  # 5000
PROFILE_NAME = dev_screen.PROFILE_NAME  # promotion-v2-watch-rect
PROFILE_DIGEST = dev_screen.PROFILE_DIGEST
CONFIG_PATH = dev_screen.DEFAULT_CONFIG  # research/apex_safety_20260926/deployment.yaml
CONFIG_SHA256 = "4146baa3a06102b8afd627b1fba8384e9a2f47aaac4a9bc96292c3eb71715aa5"
CHECKPOINT_DIR = dev_screen.DEFAULT_CHECKPOINT_DIR
CHAMPION_NAME, CHAMPION_SHA256 = dev_screen.CHAMPION
POOL = tuple(dev_screen.POOL)

ARMS = ("incumbent", "candidate")
INCUMBENT_LAMBDA = 4.0
CANDIDATE_LAMBDA = 8.0
INCUMBENT_METHOD = "free-space-veto/v7-space-preference(lambda=4.0)"
CANDIDATE_METHOD = "free-space-veto/v8-space-and-head(lambda=8.0)"
ARM_METHODS = {"incumbent": INCUMBENT_METHOD, "candidate": CANDIDATE_METHOD}
# A key every ``veto_diagnostics`` of the arm's kind carries (v7: SpacePreferenceCounters;
# v8: SpaceAndHeadCounters, which nests v7's under "v7").
DIAGNOSTICS_MARKER = {"incumbent": "rerank_changes", "candidate": "head_checks"}

V2 = "src/evaluation/safety_veto.py"
V3 = "src/evaluation/safety_veto_v3.py"
V4 = "src/evaluation/safety_veto_v4.py"
V5 = "src/evaluation/safety_veto_v5.py"
V6 = "src/evaluation/safety_veto_v6.py"
V7 = "src/evaluation/safety_veto_v7.py"
V8 = "src/evaluation/safety_veto_v8.py"
# Veto modules each arm executes, primary first. v7 imports v2, v3, v5; v8 imports v2, v3,
# v5, v6, v7, and v6 imports v4. Non-veto imports are bound by the source closure (src/).
ARM_SOURCES = {
    "incumbent": (V7, V2, V3, V5),
    "candidate": (V8, V7, V6, V5, V4, V3, V2),
}

# The released incumbent: the v7 STRICT_PASS receipt (web/backend/safety_veto_serving.py
# pins the same receipt sha256 for the served default since da951d2).
ARTIFACTS = Path("/Users/josenunez/Projects/ml/snake-dqn-artifacts")
V7_STRICT_RECEIPT = ARTIFACTS / "apex-veto-v7-strict-20261002/run-v1/output/receipt.json"
V7_STRICT_RECEIPT_SHA256 = "86ee36791e33ecad06bd525e8190d97f1c012ac6e3ede33ba05abe544f750422"
INCUMBENT_SOURCE_SHA256S = {
    V2: "1b62d15c48987584533efbefdf3fd84e1e3f2e22cfe70dbb82b43ec57169c428",
    V3: "ed3a6d860b09afd982bc6c87ea0a86566455dfcf9562133d1772e595b4bb5be1",
    V5: "d86d084e7778fc514c4932b27f3750f5f11543e3c7afa44571869407870ec86c",
    V7: "56ff7009ce2e0c4c93b6570336b35d48341757fc53b386d309b00126f67e2980",
}
# The candidate's bytes; equal to the v8 Tier-1 screen commit's (tests check git show).
SCREEN_COMMIT = "e260617876563f534001672b35e57c4db43490dd"
CANDIDATE_SOURCE_SHA256S = {
    **INCUMBENT_SOURCE_SHA256S,
    V4: "3f0881afb7ff8ff980c9b425ef40134f127cc90f1f40260aac39f2264ed44578",
    V6: "a6117cb98383f9f28bf8ebcf22d2ef63d7a03995734a36fb96bb1bf8bb1757d5",
    V8: "faf3695fa9d60550f1f681c04b8c8aba0447fecaa34cd75f16f75efe91e4ac05",
}

# ---------------------------------------------------------------- earlier namespaces

EXCLUSION_PREFIX = 1000
WEB_PURPOSES = ("watch", "play", "parity", "worlds")
_W = ("worlds",)
# Every earlier SHA-prefix domain of the dev_screen recipe (frozen copy of the v8 screen's
# EARLIER_DOMAINS, which includes the v8 screen and the v8 DEV sweep and their smokes, all
# v7 strict banks and the v7 web serving lanes; a test asserts the copy is a superset).
EARLIER_DOMAINS: Dict[str, Sequence[str]] = {
    dev_screen.SCREEN_DOMAIN: (dev_screen.SCREEN_NAMESPACE,),
    **{
        f"apex-veto-strict-{bank}-v{version}": _W
        for bank in ("dev", "final", "serving")
        for version in (1, 2, 3)
    },
    "apex-veto-strict-smoke-v1": _W,
    "apex-veto-web-serving-v1": WEB_PURPOSES,
    "apex-veto-web-serving-smoke-v1": WEB_PURPOSES,
    "apex-veto-v3-screen-v1": _W,
    "apex-veto-v3-screen-v2": _W,
    "apex-veto-v3-screen-smoke-v1": _W,
    "apex-veto-v4-screen-v1": _W,
    "apex-veto-v4-screen-smoke-v1": _W,
    "apex-veto-v5-screen-v1": _W,
    "apex-veto-v5-screen-smoke-v1": _W,
    "apex-veto-v5-strict-dev-v1": _W,
    "apex-veto-v5-strict-final-v1": _W,
    "apex-veto-v5-strict-serving-v1": _W,
    "apex-veto-v5-strict-smoke-v1": _W,
    "apex-veto-v5-web-serving-v1": WEB_PURPOSES,
    "apex-veto-v5-web-serving-smoke-v1": WEB_PURPOSES,
    "apex-veto-v6-screen-v1": _W,
    "apex-veto-v6-screen-smoke-v1": _W,
    "apex-veto-v7-dev-v1": _W,
    "apex-veto-v7-dev-smoke-v1": _W,
    "apex-veto-v7-screen-v1": _W,
    "apex-veto-v7-screen-smoke-v1": _W,
    "apex-veto-v7-strict-dev-v1": _W,
    "apex-veto-v7-strict-final-v1": _W,
    "apex-veto-v7-strict-serving-v1": _W,
    "apex-veto-v7-strict-smoke-v1": _W,
    "apex-veto-v7-web-serving-v1": WEB_PURPOSES,
    "apex-veto-v7-web-serving-smoke-v1": WEB_PURPOSES,
    "apex-veto-v8-dev-v1": _W,
    "apex-veto-v8-dev-smoke-v1": _W,
    "apex-veto-v8-screen-v1": _W,
    "apex-veto-v8-screen-smoke-v1": _W,
    "trap-horizon-dev-v1": _W,
    "trap-horizon-dev-smoke-v1": _W,
    "trap-horizon-v5-dev-v1": _W,
    "trap-horizon-v5-dev-smoke-v1": _W,
}
# Saved artifacts whose actually-played world seeds are excluded too (missing file = refuse).
OBSERVED_SEED_SOURCES = (
    ARTIFACTS / "apex-veto-v7-strict-20261002/run-v1/output/rosters.json",
    ARTIFACTS / "apex-veto-v7-strict-20261002/run-v1/intent.json",
    ARTIFACTS / "apex-veto-v7-lambda-sweep-20261002/run-v1/intent.json",
    ARTIFACTS / "apex-veto-v7-screen-20261002/run-v1/intent.json",
    ARTIFACTS / "apex-veto-v7-serving-20261002/run-v1/intent.json",
    ARTIFACTS / "apex-veto-v8-lambda-sweep-20261002/run-v1/shard-0/intent.json",
    ARTIFACTS / "apex-veto-v8-lambda-sweep-20261002/run-v1/shard-1/intent.json",
    ARTIFACTS / "apex-veto-v8-lambda-sweep-20261002/run-v1/shard-2/intent.json",
    ARTIFACTS / "apex-veto-v8-lambda-sweep-20261002/run-v1/merged/summary.json",
    ARTIFACTS / "apex-veto-v8-screen-20261002/run-v1/shard-0/intent.json",
    ARTIFACTS / "apex-veto-v8-screen-20261002/run-v1/shard-1/intent.json",
    ARTIFACTS / "apex-veto-v8-screen-20261002/run-v1/shard-2/intent.json",
    ARTIFACTS / "apex-veto-v8-screen-20261002/run-v1/merged/summary.json",
)
SEED_KEYS = ("world_seed", "seeds", "paired_seeds", "world_seeds", "final_seeds")


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _collect_seeds(value: Any, out: set, under_key: bool = False) -> None:
    if isinstance(value, Mapping):
        for key, item in value.items():
            _collect_seeds(item, out, under_key or key in SEED_KEYS)
    elif isinstance(value, list):
        for item in value:
            _collect_seeds(item, out, under_key)
    elif under_key and isinstance(value, int) and not isinstance(value, bool):
        out.add(int(value))


def observed_seeds(sources: Sequence[Path] = OBSERVED_SEED_SOURCES) -> Dict[str, List[int]]:
    out: Dict[str, List[int]] = {}
    for path in sources:
        path = Path(path)
        require(path.is_file(), f"observed-seed source missing: {path}")
        seeds: set = set()
        _collect_seeds(json.loads(path.read_text(encoding="utf-8")), seeds)
        require(bool(seeds), f"observed-seed source has no seeds: {path}")
        out[f"observed:{path}"] = sorted(seeds)
    return out


def excluded_seeds() -> Dict[str, List[int]]:
    """(5) Every earlier namespace: first 1000 seeds of each earlier domain/purpose, the
    task-aligned challenger namespaces, the strict pilot's observed seeds, seeds 0..999 and
    the seeds saved in every earlier v7/v8 artifact (the disjointness preflight the v8 screen
    ran, plus the v8 screen and DEV sweep themselves)."""
    out: Dict[str, List[int]] = {
        f"{domain}/{purpose}[0:{EXCLUSION_PREFIX}]": [
            dev_screen.uint32_seed(domain, purpose, i) for i in range(EXCLUSION_PREFIX)
        ]
        for domain, purposes in EARLIER_DOMAINS.items()
        for purpose in purposes
    }
    for name, values in dev_screen.challenger_namespaces().items():
        out[f"challenger:{name}"] = values
    pilot = Path(dev_screen.DEFAULT_PILOT_OUTPUT)
    require(pilot.is_dir(), f"strict pilot output {pilot} missing")
    for stage, values in dev_screen.observed_pilot_seeds(pilot).items():
        require(bool(values), f"strict pilot {stage} has no observed seeds")
        out[f"strict-pilot-observed:{stage}"] = values
    out["small-integer-seeds-0-999"] = list(range(1000))
    out.update(observed_seeds())
    return out


# ---------------------------------------------------------------- arm identities


def _receipt_identity() -> Dict[str, Any]:
    """The released v7's identity, read from the v7 STRICT_PASS receipt (fail closed)."""
    require(V7_STRICT_RECEIPT.is_file(), f"v7 strict receipt {V7_STRICT_RECEIPT} missing")
    actual = sha256_file(V7_STRICT_RECEIPT)
    require(actual == V7_STRICT_RECEIPT_SHA256, f"v7 strict receipt sha256 {actual} not pinned")
    receipt = json.loads(V7_STRICT_RECEIPT.read_text(encoding="utf-8"))
    decision = receipt.get("decision") or {}
    require(
        receipt.get("receipt") == "strict-pass-receipt-only"
        and decision.get("passes") is True
        and decision.get("valid") is True,
        "the v7 strict receipt is not a valid STRICT_PASS",
    )
    cand = receipt["candidate"]
    return {
        "receipt_path": str(V7_STRICT_RECEIPT),
        "receipt_sha256": actual,
        "checkpoint_sha256": cand["checkpoint_sha256"],
        "wrapper": cand["wrapper"],
        "descriptor": cand["wrapper_identity"]["descriptor"],
        "source_sha256s": dict(cand["wrapper_identity"]["source_sha256s"]),
    }


def arm_identities(repo: Path | None = None) -> Dict[str, Dict[str, Any]]:
    """(1) Each arm's identity, computed from the files (never typed in), fail closed.

    Incumbent: must equal the v7 STRICT_PASS receipt's candidate (method, descriptor,
    checkpoint, the four veto module sha256s). Candidate: v8 at lambda 8 with every veto
    module it executes pinned to :data:`CANDIDATE_SOURCE_SHA256S`.
    """
    from src.evaluation.safety_veto_v7 import SpacePreferenceVeto
    from src.evaluation.safety_veto_v8 import SpaceAndHeadVeto

    root = Path(repo) if repo is not None else Path(__file__).resolve().parents[2]
    released = _receipt_identity()
    champion = sha256_file(CHECKPOINT_DIR / CHAMPION_NAME)
    require(champion == CHAMPION_SHA256, f"champion checkpoint sha256 {champion} differs")
    descriptors = {
        "incumbent": SpacePreferenceVeto(INCUMBENT_LAMBDA).descriptor(),
        "candidate": SpaceAndHeadVeto(CANDIDATE_LAMBDA).descriptor(),
    }
    pinned = {"incumbent": INCUMBENT_SOURCE_SHA256S, "candidate": CANDIDATE_SOURCE_SHA256S}
    out: Dict[str, Dict[str, Any]] = {}
    for arm in ARMS:
        sources = {rel: sha256_file(root / rel) for rel in ARM_SOURCES[arm]}
        expected = {rel: pinned[arm][rel] for rel in ARM_SOURCES[arm]}
        require(sources == expected, f"{arm} veto sources differ from the pinned bytes")
        require(descriptors[arm]["method"] == ARM_METHODS[arm], f"{arm} veto method differs")
        out[arm] = {
            "method": ARM_METHODS[arm],
            "descriptor": descriptors[arm],
            "checkpoint_name": CHAMPION_NAME,
            "checkpoint_sha256": champion,
            "source_sha256": sources[ARM_SOURCES[arm][0]],
            "source_sha256s": sources,
            "install": (
                "dev_screen.hero_veto_installer(install_space_preference_veto(hero, 4.0))"
                if arm == "incumbent"
                else "dev_screen.hero_veto_installer(install_space_and_head_veto(hero, 8.0))"
            )
            + " around rollout(hero_safety_veto=True); opponents unwrapped",
        }
    inc = out["incumbent"]
    require(
        inc["method"] == released["wrapper"]
        and inc["descriptor"] == released["descriptor"]
        and inc["source_sha256s"] == released["source_sha256s"]
        and inc["checkpoint_sha256"] == released["checkpoint_sha256"],
        "incumbent is not the released v7 bound by the v7 STRICT_PASS receipt",
    )
    require(
        descriptors["candidate"].get("space_preference_lambda") == CANDIDATE_LAMBDA
        and descriptors["candidate"].get("head_avoidance") is True,
        "candidate is not v8 at lambda 8 with head avoidance",
    )
    inc["release_binding"] = {
        "v7_strict_receipt_path": released["receipt_path"],
        "v7_strict_receipt_sha256": released["receipt_sha256"],
        "served_default_since": "da951d2 (web/backend/safety_veto_serving.py pins this receipt)",
    }
    out["candidate"]["screen_binding"] = {
        "v8_screen_commit": SCREEN_COMMIT,
        "v8_screen_decision": "ADVANCE (Tier-1, non-authoritative)",
        "reference_lambda": "not installed (diagnostic only in the screen; not in descriptor)",
    }
    return out


# ---------------------------------------------------------------- rosters


@functools.lru_cache(maxsize=4)
def _bank_rows(domain: str) -> Dict[tuple, Dict[str, Any]]:
    """Strict balanced rosters of a domain's first ``N_MAX_CAP`` worlds, keyed by world.

    Slot members rotate by world index, so rows of a prefix bank equal the prefix rows of
    the full bank (tests check it); the calibration (16) and final (N_max) banks are
    prefixes of these 300.
    """
    seeds = seed_bank(domain, N_MAX_CAP)
    index = {seed: i for i, seed in enumerate(seeds)}
    require(len(index) == len(seeds), f"seed collision inside {domain}")
    rows = {}
    for row in dev_screen._design_rows(seeds):
        rows[(row["mix"], index[int(row["world_seed"])])] = row
    return rows


def build_row(phase: str, mix: str, world_index: int, world_seed: int) -> Dict[str, Any]:
    """(3) The strict balanced roster of the world (dev_screen._design_rows), plus its index."""
    require(phase in NAMESPACES, f"unknown phase {phase}")
    row = _bank_rows(NAMESPACES[phase])[(mix, int(world_index))]
    require(int(row["world_seed"]) == int(world_seed), "roster seed differs from the bank")
    return {**row, "world_index": int(world_index)}


# ---------------------------------------------------------------- episodes


def worker_setup(intent: Mapping[str, Any]) -> Dict[str, Any]:
    """Per worker: torch threads, pinned config, profile digest, verified checkpoints."""
    from src.core.config_loader import load_and_initialize_config
    from src.scripts.tournament_eval import evaluation_profile_for_name

    dev_screen._configure_torch()
    require(sha256_file(CONFIG_PATH) == CONFIG_SHA256, "deployment config drift")
    load_and_initialize_config(str(CONFIG_PATH))
    profile = evaluation_profile_for_name(PROFILE_NAME, HORIZON)
    require(profile.digest == PROFILE_DIGEST, "evaluation profile digest drift")
    paths = verify_pool()
    return {
        "profile": profile,
        "profile_ref": {"descriptor": profile.descriptor(), "digest": profile.digest},
        "lookup": dev_screen.agent_lookup(paths),
        "arms": intent["arms"],
    }


def verify_pool() -> Dict[str, str]:
    """sha256 -> path of every pool checkpoint, each re-hashed (fail closed)."""
    paths = {}
    for name, expected in POOL:
        path = CHECKPOINT_DIR / name
        actual = sha256_file(path)
        require(actual == expected, f"checkpoint {name} sha256 {actual} != pinned {expected}")
        paths[expected] = str(path)
    return paths


def install_incumbent(hero: Any) -> Any:
    from src.evaluation.safety_veto_v7 import install_space_preference_veto

    return install_space_preference_veto(hero, INCUMBENT_LAMBDA)


def install_candidate(hero: Any) -> Any:
    from src.evaluation.safety_veto_v8 import install_space_and_head_veto

    return install_space_and_head_veto(hero, CANDIDATE_LAMBDA)


INSTALLERS = {"incumbent": install_incumbent, "candidate": install_candidate}


def episode_runner(
    episode: Mapping[str, Any], row: Mapping[str, Any], context: Mapping[str, Any]
) -> Dict[str, Any]:
    """(2) One H5000 hero episode of the arm on the world; strict record shape enforced.

    Returns the rollout record plus ``veto_diagnostics`` (the arm's counters; reported, not
    gated). Any shape or identity problem raises (the worker dies; the run is INVALID_STOP).
    """
    from src.evaluation.strict_promotion import (
        _expected_world_identity,
        validate_strict_world_record,
    )
    from src.scripts.tournament_eval import rollout

    arm = episode["arm"]
    require(arm in INSTALLERS, f"unknown arm {arm}")
    require(int(row["world_seed"]) == int(episode["world_seed"]), "row/episode seed mismatch")
    verify_pool()  # the bytes rollout loads are the pinned ones, every episode
    lookup = context["lookup"]
    hero = lookup[CHAMPION_SHA256]
    opponents = [lookup[slot["member_sha256"]] for slot in row["slots"]]
    with dev_screen.hero_veto_installer(INSTALLERS[arm]) as installed:
        record = rollout(
            hero,
            opponents,
            HORIZON,
            int(row["world_seed"]),
            profile=context["profile"],
            world_identity=_expected_world_identity(row),
            mix_id=row["mix"],
            hero_safety_veto=True,
        )
    require(len(installed) == 1, f"the {arm} veto was not installed exactly once")
    descriptor = context["arms"][arm]["descriptor"]
    try:
        validate_strict_world_record(
            record, context["profile_ref"], row, candidate_wrapper=descriptor
        )
    except Exception as exc:  # noqa: BLE001 - re-raised as a run failure
        raise StrictRunError(f"{episode['episode_id']}: strict record shape: {exc}") from exc
    return {**dict(record), "veto_diagnostics": installed[0].diagnostics_record()}


def validate_record(entry: Mapping[str, Any], row: Mapping[str, Any]) -> List[str]:
    """(4) Envelope-level checks on top of the strict validator run in ``episode_runner``."""
    problems: List[str] = []
    arm = entry.get("arm")
    record = entry.get("record") or {}
    probe = (record.get("probes") or {}).get("safety_veto") or {}
    if arm not in ARM_METHODS:
        return [f"unknown arm {arm!r}"]
    if probe.get("method") != ARM_METHODS[arm]:
        problems.append(f"{arm} probe method {probe.get('method')!r}")
    diagnostics = record.get("veto_diagnostics")
    if not isinstance(diagnostics, Mapping) or DIAGNOSTICS_MARKER[arm] not in diagnostics:
        problems.append(f"{arm} veto_diagnostics of the wrong kind")
    if arm == "incumbent" and isinstance(diagnostics, Mapping) and "head_checks" in diagnostics:
        problems.append("incumbent carries v8 diagnostics")
    identity = record.get("world_identity") or {}
    if identity.get("seed") != row.get("world_seed") or identity.get("mix_id") != row.get("mix"):
        problems.append("world identity differs from the roster row")
    if record.get("seed") != row.get("world_seed"):
        problems.append("record seed differs from the roster row")
    return problems


SPEC = StudySpec(
    study_id=STUDY_ID,
    schema=SCHEMA,
    namespaces=dict(NAMESPACES),
    arm_identities=arm_identities,
    episode_runner=episode_runner,
    excluded_seeds=excluded_seeds,
    protocol_path=f"{PACKAGE}/protocol.md",
    oc_report_path=f"{PACKAGE}/operating_characteristics.json",
    band_cost_report_path=f"{PACKAGE}/look1_band_cost.json",
    mixes=MIXES,
    scripted_mix=SCRIPTED_MIX,
    primary_metric=PRIMARY_METRIC,
    ni_fraction=NI_FRACTION,
    bands=survival_bands(MIXES, below=BAND_BELOW, above=BAND_ABOVE),
    worker_setup=worker_setup,
    build_row=build_row,
    validate_record=validate_record,
    closure_roots=(*DEFAULT_CLOSURE_ROOTS, "research/apex_safety_20260926", PACKAGE),
)
